### PR TITLE
Update to netstandard2 and new project format

### PR DESCRIPTION
**Pull request by maikebing**

### CODE REVIEW

**Comment by gralin** [comment]
@maikebing thank you for contribution. I will check if everything is ok, especially with the continous integration and merge it soon.

**Comment by JohnnBlade** [comment]
I have been working on a clean version of the BACnet code, and its in .Net Core but can be set to be used in .net Standaard

**Comment by JohnnBlade** [comment]
i am porting all of this code to .Net core and refactoring it all, inc naming conventions

**Comment by gralin** [comment]
Hi @JohnnBlade, thanks for the heads up. Are you planning on contributing back to this repo or are you planning on maintaining it as a fork?

**Comment by JohnnBlade** [comment]
> Hi @JohnnBlade, thanks for the heads up. Are you planning on contributing back to this repo or are you planning on maintaining it as a fork?

Greets Gralin,

I would like that to help out a bit, i just recently found out about BACnet, but when i saw the code and the naming conventions used, i wanted to make it more better, and also refactor and clean up the different coding styles used.

for now i just downloaded this project in zip and started to clean up the whole code, but im not done yet , i do have it on my github.

only thing is that i dont have any BACnet hardware and im testing with software devices instead of real oners so testing is limited for me, but im willing to help out

**Comment by gralin** [comment]
@JohnnBlade great to hear you are interested in contributing, any help is always appreciated! Speaking of current codebase and conventions, please check out this comment to learn more about the history of this project and get the idea why it is how it is: https://github.com/ela-compil/BACnet/pull/25#discussion_r172821867

One thing I'm afraid is that your huge refactor will be unreviewable and unless you deliver it in a batch of separate PRs, I won't be able to merge with clear conscience 🙈 Do you think this is something you will be able to do? Also, which branch did you download? There is a `v2` branch with a lot of contribution from @DarkStarDS9 and there is also an unmerged PR from him (#25) that I would like to include. That codebase is already way better then `master`. It's my fault that I didn't find enough time after work to maintain this repo but I will try to do better.

**Pull request merged**
